from pathlib import Path


PROJECT = "visionops-multicloud"


def test_readme_explains_real_structure_and_gitflow() -> None:
    readme = Path("README.md").read_text(encoding="utf-8")
    assert "## Estructura del proyecto" in readme
    assert f"{PROJECT}/" in readme
    assert "diagrams/" in readme
    assert "infra/" in readme
    assert "docs/evidence/local-100k.json" in readme
    assert "## GitFlow" in readme
    assert "```mermaid\ngitGraph" in readme
    assert "feature/*" in readme
    assert "release/*" in readme
    assert "hotfix/*" in readme
    assert "El repositorio local se inicializa" not in readme
    assert "URL-PENDIENTE" not in readme
    assert "PENDING_REMOTE" not in readme
    assert f"https://github.com/danielyatacoblas/{PROJECT}" in readme
    assert readme.count("```") % 2 == 0
    for relative in (
        ".github/workflows/ci.yml",
        "data/sample",
        "diagrams/architecture.json",
        "docs/evidence/local-100k.json",
        "infra/aws",
        "infra/azure",
        "infra/gcp",
        "scripts/benchmark_api.py",
        "src",
        "tests",
        "compose.yaml",
        "Dockerfile.api",
    ):
        assert Path(relative).exists(), relative


def test_public_process_docs_have_no_assistant_attribution_or_emojis() -> None:
    content = "\n".join(
        path.read_text(encoding="utf-8")
        for path in (Path("README.md"), Path("CONTRIBUTING.md"))
    )
    lowered = content.lower()
    forbidden_terms = (
        "clau" + "de",
        "anthro" + "pic",
        "co-authored" + "-by",
        "generated by " + "codex",
    )
    for forbidden in forbidden_terms:
        assert forbidden not in lowered
    assert not any(
        0x1F300 <= ord(character) <= 0x1FAFF or 0x2600 <= ord(character) <= 0x27BF
        for character in content
    )
